version: '2'
services:
  # jenkins:
  #   image: "jenkins:latest"
  #   container_name: "checkmate_jenkins"
  #   ports:
  #     - "8080:8080"
  #     - "50000:50000"
  #   volumes:
  #     - "$PWD/jenkins:/var/jenkins_home"
  backend:
    ports:
    - "8000:8000"
    build:
      context: ./backend
    volumes:
      - "./backend:/checkmate"
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - config/local/vars.env
    command: 'bash -c "cd /checkmate && ./manage.py runserver 0.0.0.0:8000"'
  web:
    ports:
      - "3000:3000"
    build:
      context: ./web
    volumes:
      - "./web:/checkmate"
    command: 'bash -c "cd /checkmate && npm start"'
  web_styles:
    build:
      context: ./web
    volumes:
      - "./web/src/styles:/checkmate/src/styles"
    working_dir: '/checkmate/src/styles'
    command: 'sass --watch styles.sass:styles.css'
  landing_styles:
    build:
      context: ./web
    volumes:
      - "./landing/static/css/:/landing/static/css"
    working_dir: '/landing/static/css'
    command: 'sass --watch styles.sass:styles.css'
