# Generated by Django 3.0.3 on 2020-02-08 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CheckListRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklists.CheckList')),
            ],
        ),
        migrations.CreateModel(
            name='CheckListRunItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_checked', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField()),
                ('checklist_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklists.CheckListRun')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='CheckListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklists.CheckList')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
