# Generated by Django 3.0.3 on 2020-02-09 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklists.CheckList'),
        ),
        migrations.AlterField(
            model_name='checklistrunitem',
            name='checklist_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklists.CheckListRun'),
        ),
    ]
