# Generated by Django 3.0.3 on 2020-02-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_auto_20200209_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='is_latest_run_complete',
            field=models.BooleanField(default=1, verbose_name=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checklistrun',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
