# Generated by Django 3.0.3 on 2020-02-09 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0003_auto_20200209_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='latest_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_run_of', to='checklists.CheckListRun'),
        ),
    ]
