# Generated by Django 3.0.3 on 2020-02-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0004_checklist_latest_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='is_latest_run_complete',
            field=models.BooleanField(default=False),
        ),
    ]
