# Generated by Django 3.0.3 on 2020-02-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0007_checklist_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklistrun',
            old_name='is_complete',
            new_name='is_closed',
        ),
        migrations.AlterField(
            model_name='checklist',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
