# Generated by Django 3.0.4 on 2020-03-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0008_auto_20200229_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistrun',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
