# Generated by Django 3.0.4 on 2020-03-07 00:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0009_checklistrun_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistrun',
            options={'ordering': ('created_at',)},
        ),
        migrations.AddField(
            model_name='checklistrun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 3, 7, 0, 7, 23, 212563, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
