# Generated by Django 3.0.4 on 2020-03-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0010_auto_20200307_0007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistrun',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='checklistrun',
            name='name',
        ),
        migrations.AddField(
            model_name='checklistrun',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='checklistrun',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
